apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app: kuard
      version: "2"
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
        version: "2"
    spec:
      containers:
        - name: kuard
          image: "gcr.io/kuar-demo/kuard-amd64:2"
